/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface SplitPane {
    'direction'?: "horizontal" | "vertical";
  }
}

declare global {


  interface HTMLSplitPaneElement extends Components.SplitPane, HTMLStencilElement {}
  var HTMLSplitPaneElement: {
    prototype: HTMLSplitPaneElement;
    new (): HTMLSplitPaneElement;
  };
  interface HTMLElementTagNameMap {
    'split-pane': HTMLSplitPaneElement;
  }
}

declare namespace LocalJSX {
  interface SplitPane extends JSXBase.HTMLAttributes<HTMLSplitPaneElement> {
    'direction'?: "horizontal" | "vertical";
  }

  interface IntrinsicElements {
    'split-pane': SplitPane;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


