/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  StyleType,
} from './utils';

export namespace Components {
  interface IconDot {
    'type': StyleType;
  }
}

declare global {


  interface HTMLIconDotElement extends Components.IconDot, HTMLStencilElement {}
  var HTMLIconDotElement: {
    prototype: HTMLIconDotElement;
    new (): HTMLIconDotElement;
  };
  interface HTMLElementTagNameMap {
    'icon-dot': HTMLIconDotElement;
  }
}

declare namespace LocalJSX {
  interface IconDot extends JSXBase.HTMLAttributes<HTMLIconDotElement> {
    'type'?: StyleType;
  }

  interface IntrinsicElements {
    'icon-dot': IconDot;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


