/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ImgSlideshow {
    /**
    * Optionally specify a value to place before *all* paths provided in `src`. For example:  ```html <img-slideshow base-url="https://picsum.photos" src='["/200/300", "/200/300"]' /> ``` would be the same as  ```html <img-slideshow src='["https://picsum.photos/200/300", "https://picsum.photos/200/300"]' /> ```
    */
    'baseUrl'?: string;
    /**
    * Set the visibility duration (ms) of each slide.
    */
    'interval'?: number;
    /**
    * JSON-formatted string array of image URLs.  ```html <img-slideshow src='["https://picsum.photos/200/300", "https://picsum.photos/200/300"]' /> ```
    */
    'src': string;
    /**
    * Optionally request that all URLs are filtered by a HTTP 200 status code.  For example:  ```html <img-slideshow src='["/exists/1.png", "/notfound/1.png", "/exists/2.png"]' validate-urls /> ```  would be the same as  ```html <img-slideshow src='["/exists/1.png", "/exists/2.png"]' validate-urls /> ```
    */
    'validateUrls'?: boolean;
  }
}

declare global {


  interface HTMLImgSlideshowElement extends Components.ImgSlideshow, HTMLStencilElement {}
  var HTMLImgSlideshowElement: {
    prototype: HTMLImgSlideshowElement;
    new (): HTMLImgSlideshowElement;
  };
  interface HTMLElementTagNameMap {
    'img-slideshow': HTMLImgSlideshowElement;
  }
}

declare namespace LocalJSX {
  interface ImgSlideshow extends JSXBase.HTMLAttributes<HTMLImgSlideshowElement> {
    /**
    * Optionally specify a value to place before *all* paths provided in `src`. For example:  ```html <img-slideshow base-url="https://picsum.photos" src='["/200/300", "/200/300"]' /> ``` would be the same as  ```html <img-slideshow src='["https://picsum.photos/200/300", "https://picsum.photos/200/300"]' /> ```
    */
    'baseUrl'?: string;
    /**
    * Set the visibility duration (ms) of each slide.
    */
    'interval'?: number;
    'onSlidetransition'?: (event: CustomEvent<any>) => void;
    /**
    * JSON-formatted string array of image URLs.  ```html <img-slideshow src='["https://picsum.photos/200/300", "https://picsum.photos/200/300"]' /> ```
    */
    'src'?: string;
    /**
    * Optionally request that all URLs are filtered by a HTTP 200 status code.  For example:  ```html <img-slideshow src='["/exists/1.png", "/notfound/1.png", "/exists/2.png"]' validate-urls /> ```  would be the same as  ```html <img-slideshow src='["/exists/1.png", "/exists/2.png"]' validate-urls /> ```
    */
    'validateUrls'?: boolean;
  }

  interface IntrinsicElements {
    'img-slideshow': ImgSlideshow;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


